services:
  nginx:
    image: nginx
    container_name: nginx-proxy
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/usr/src/app/static
    depends_on:
      - app
