services:
  nginx:
    image: nginx
    container_name: nginx-proxy
    restart: always
    ports:
      - "8008:3000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/usr/src/app/static
    depends_on:
      - app

  app:
    build: .
    container_name: node-app
    volumes:
      - .:/usr/src/app
    restart: always
    expose:
      - "3000"
